version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --reload
    ports:
      - 8000:8000
    env_file:
      - ./docker/backend/.env
    volumes:
      - ./backend:/srv/app
      - public_html:/var/www/html
    depends_on:
      - db
      
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    env_file: ./docker/postgres/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - public_html:/var/www/html
    depends_on:
      - backend
      - db
  
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    command: npm run dev
    ports:
      - 3000:3000
    env_file:
      - ./docker/frontend/.env
    volumes:
      - ./frontend/:/srv/app
      - public_html:/var/www/html
    depends_on:
      - backend
      - db

volumes:
  postgres_data:
  public_html: